### ISSUE TITLE
No code contribution

### ISSUE THREAD

**Issue by Radiosnack** [MLSA-UETP/HacktoberFest-22#13]
Would like add some content regarding AI/ML (No code).. Kindly assign this issue to me

**Comment by Hamas-ur-Rehman** [comment]
you can go to the readme of the AIML folder and populate it we need to make it presentable and explain the purpose of the folder. You can then create a pull request afterwards and then I can accept it as hacktoberfest accepted

**Comment by Radiosnack** [comment]
@Hamas-ur-Rehman Created #18 PR . kindly review it.
